package searcher

import (
	"GoAnime/sources"
	"encoding/json"
	"testing"
)

func TestSearch(t *testing.T) {
	testJsonArr := []string{
		"{\"title\":\"Danganronpa The Animation\",\"plot_summary\":\"A group of 15 elite high school students are gathered at a very special, high class high school. To graduate from this high school essentially means you’ll succeed in life, but graduating is very difficult. The school is presided over by a bear called Monokuma, and he explains to them that their graduation hinges around committing a murder. The only way to graduate is to kill one of your classmates and get away with it. If the other classmates discover the identity of the killer, the killer is the only one executed. However, if they fail to catch the killer, only the killer graduates and the others are annihilated. Which of the 15 will survive the bloodbath to come?\",\"other_name\":\"ダンガンロンパ 希望の学園と絶望の高校生 THE ANIMATION\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2013,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-1\"},{\"number\":2,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-2\"},{\"number\":3,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-3\"},{\"number\":4,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-4\"},{\"number\":5,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-5\"},{\"number\":6,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-6\"},{\"number\":7,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-7\"},{\"number\":8,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-8\"},{\"number\":9,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-9\"},{\"number\":10,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-10\"},{\"number\":11,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-11\"},{\"number\":12,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-12\"},{\"number\":13,\"link\":\"https://gogoanime.io/-danganronpa-the-animation-episode-13\"}]}",
		"{\"title\":\"Danganronpa: The Animation (Dub)\",\"plot_summary\":\"A group of 15 elite high school students are gathered at a very special, high class high school. To graduate from this high school essentially means you'll succeed in life, but graduating is very difficult. The school is presided over by a bear called Monokuma, and he explains to them that their graduation hinges around committing a murder. The only way to graduate is to kill one of your classmates and get away with it. If the other classmates discover the identity of the killer, the killer is the only one executed. However, if they fail to catch the killer, only the killer graduates and the others are annihilated. Which of the 15 will survive the bloodbath to come?\",\"other_name\":\"ダンガンロンパ 希望の学園と絶望の高校生 THE ANIMATION\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2013,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-1\"},{\"number\":2,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-2\"},{\"number\":3,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-3\"},{\"number\":4,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-4\"},{\"number\":5,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-5\"},{\"number\":6,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-6\"},{\"number\":7,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-7\"},{\"number\":8,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-8\"},{\"number\":9,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-9\"},{\"number\":10,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-10\"},{\"number\":11,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-11\"},{\"number\":12,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-12\"},{\"number\":13,\"link\":\"https://gogoanime.io/danganronpa-the-animation-dub-episode-13\"}]}",
		"{\"title\":\"Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen\",\"plot_summary\":\"The world was close to being destroyed by Ultimate Despair, who caused \\\"The Biggest, Most Awful, Most Tragic Event in Human History.\\\" In order to save this world from the event's chaos, the Future Foundation was formed. Although the organization continues its activities to restore the world, Makoto Naegi is under suspicion of treason due to him shielding a Remnant of Despair.\\n\\nThe Future Foundation members had gathered together to decide on his punishment, but they all end up getting trapped inside the place they were meeting by Monokuma, who demands that they begin the \\\"Final Killing.\\\" They have strange bangles put on their wrists, and are given tranquilizers when a certain time arrives. To make things worse, there apparently is a real traitor amongst their ranks who is coming to kill the members of the Future Foundation.\\n\\nIn this game where class trials don't exist, the only way to get rid of the traitor is to find him and kill him off. Naegi is forced to face the ultimate death game, where it's kill or be killed. The tale of despair in which hope kills hope begins.\",\"other_name\":\"Danganronpa 3: The End of Hope's Peak High School - Future Arc, ダンガンロンパ3 -The End of 希望ヶ峰学園- 未来編\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2016,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-1\"},{\"number\":2,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-2\"},{\"number\":3,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-3\"},{\"number\":4,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-4\"},{\"number\":5,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-5\"},{\"number\":6,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-6\"},{\"number\":7,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-7\"},{\"number\":8,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-8\"},{\"number\":9,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-9\"},{\"number\":10,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-10\"},{\"number\":11,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-11\"},{\"number\":12,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-episode-12\"}]}",
		"{\"title\":\"Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen\",\"plot_summary\":\"Side: Hope of Danganronpa 3: The End of Kibougamine Gakuen. Kibou-hen serves the finale for the entire Danganronpa 3 anime series\",\"other_name\":\"Danganronpa 3: The End of Hope's Peak High School - Hope Arc, Danganronpa 3: The End of Hope's Peak Academy - Hope Volume, ダンガンロンパ３-The End of 希望ヶ峰学園-希望編\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2016,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-kibou-hen-episode-1\"}]}",
		"{\"title\":\"Super Danganronpa 2.5: Komaeda Nagito to Sekai no Hakaimono\",\"plot_summary\":\"Nagito Komaeda wakes up after experiencing death in the Neo World Program. What kind of world he is seeing and why did he wake up?\\n\\nNagito appears to be in a strange world, including students who have been seen before as well as people who never existed. He is an ordinary boy with no Ultimate Luck, attending an ordinary school. Constrained by being the protagonist, he thinks that having a big talent would interrupt his happiness. He believes that living an ordinary life, being moderately happy, while watching his classmates have a normal youth is what's wonderful.\\n\\nHowever, one day, a boy calling himself \\\"The Destroyer of the World\\\" appears, having the form of red-eyed Hajime Hinata. He begins the destruction of Nagito's world...\\n\\n(Source: Danganronpa Wikia)\",\"other_name\":\"Super Danganronpa 2.5: Nagito Komaeda and the Destroyer of the World, スーパーダンガンロンパ2.5 狛枝凪斗と世界の破壊者\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2017,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/super-danganronpa-2-5-komaeda-nagito-to-sekai-no-hakaimono-episode-1\"}]}",
		"{\"title\":\"Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen\",\"plot_summary\":\"Hope's Peak Academy is a special school, recognized by the government, that was established in order to gather and nurture top-class students who excel in various fields. This school has two courses: The main course, and the preparatory course. Anyone with the money can enter the preparatory course, even if they don't have any special skills. The 77th class of the main course is filled with students who not only have unique abilities, but unique personalities as well.\\n\\nHowever, the students learned that \\\"Talent isn't the most important thing in life; it's to involve yourself with people and make yourself a better person while making memories.\\\" However, little did they know that a mysterious project and discrimination of the courses were happening right under their noses.\\n\\nHajime Hinata, a boy from the preparatory class who craves for an ability. The fateful meeting he has drives the future of the school into an unimaginable direction. This is the story of what happened up until the \\\"The Biggest, Most Awful, Most Tragic Event in Human History.\\\" This is a story of hope that ends in despair.\",\"other_name\":\"Danganronpa 3: The End of Hope's Peak High School - Despair Arc, ダンガンロンパ3 -The End of 希望ヶ峰学園- 絶望編\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2016,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-1\"},{\"number\":2,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-2\"},{\"number\":3,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-3\"},{\"number\":4,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-4\"},{\"number\":5,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-5\"},{\"number\":6,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-6\"},{\"number\":7,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-7\"},{\"number\":8,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-8\"},{\"number\":9,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-9\"},{\"number\":10,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-10\"},{\"number\":11,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-episode-11\"}]}",
		"{\"title\":\"Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen (Dub)\",\"plot_summary\":\"The world was close to being destroyed by Ultimate Despair, who caused \\\"The Biggest, Most Awful, Most Tragic Event in Human History.\\\" In order to save this world from the event's chaos, the Future Foundation was formed. Although the organization continues its activities to restore the world, Makoto Naegi is under suspicion of treason due to him shielding a Remnant of Despair.\\n\\nThe Future Foundation members had gathered together to decide on his punishment, but they all end up getting trapped inside the place they were meeting by Monokuma, who demands that they begin the \\\"Final Killing.\\\" They have strange bangles put on their wrists, and are given tranquilizers when a certain time arrives. To make things worse, there apparently is a real traitor amongst their ranks who is coming to kill the members of the Future Foundation.\\n\\nIn this game where class trials don't exist, the only way to get rid of the traitor is to find him and kill him off. Naegi is forced to face the ultimate death game, where it's kill or be killed. The tale of despair in which hope kills hope begins.\",\"other_name\":\"Danganronpa 3: The End of Hope's Peak High School - Future Arc, ダンガンロンパ3 -The End of 希望ヶ峰学園- 未来編\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2016,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-1\"},{\"number\":2,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-2\"},{\"number\":3,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-3\"},{\"number\":4,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-4\"},{\"number\":5,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-5\"},{\"number\":6,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-6\"},{\"number\":7,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-7\"},{\"number\":8,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-8\"},{\"number\":9,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-9\"},{\"number\":10,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-10\"},{\"number\":11,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-11\"},{\"number\":12,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-mirai-hen-dub-episode-12\"}]}",
		"{\"title\":\"Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen (Dub)\",\"plot_summary\":\"Side: Hope of Danganronpa 3: The End of Kibougamine Gakuen. Kibou-hen serves the finale for the entire Danganronpa 3 anime series\",\"other_name\":\"Danganronpa 3: The End of Hope's Peak High School - Hope Arc, Danganronpa 3: The End of Hope's Peak Academy - Hope Volume, ダンガンロンパ３-The End of 希望ヶ峰学園-希望編\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2016,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-kibou-hen-dub-episode-1\"}]}",
		"{\"title\":\"Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen (Dub)\",\"plot_summary\":\"Hope's Peak Academy is a special school, recognized by the government, that was established in order to gather and nurture top-class students who excel in various fields. This school has two courses: The main course, and the preparatory course. Anyone with the money can enter the preparatory course, even if they don't have any special skills. The 77th class of the main course is filled with students who not only have unique abilities, but unique personalities as well.\\n\\nHowever, the students learned that \\\"Talent isn't the most important thing in life; it's to involve yourself with people and make yourself a better person while making memories.\\\" However, little did they know that a mysterious project and discrimination of the courses were happening right under their noses.\\n\\nHajime Hinata, a boy from the preparatory class who craves for an ability. The fateful meeting he has drives the future of the school into an unimaginable direction. This is the story of what happened up until the \\\"The Biggest, Most Awful, Most Tragic Event in Human History.\\\" This is a story of hope that ends in despair.\",\"other_name\":\"Danganronpa 3: The End of Hope's Peak High School - Despair Arc, ダンガンロンパ3 -The End of 希望ヶ峰学園- 絶望編\",\"type\":\"\",\"genre\":[\"Action\",\"Horror\",\"Mystery\",\"Psychological\"],\"release_year\":2016,\"status\":1,\"episodes\":[{\"number\":1,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-1\"},{\"number\":2,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-2\"},{\"number\":3,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-3\"},{\"number\":4,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-4\"},{\"number\":5,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-5\"},{\"number\":6,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-6\"},{\"number\":7,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-7\"},{\"number\":8,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-8\"},{\"number\":9,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-9\"},{\"number\":10,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-10\"},{\"number\":11,\"link\":\"https://gogoanime.io/danganronpa-3-the-end-of-kibougamine-gakuen-zetsubou-hen-dub-episode-11\"}]}",
	}

	testPhrase := "danganronpa"
	animes, err := Search(testPhrase, sources.GoGoAnime)
	if err != nil {
		t.Errorf("searcher: couldn't search for: %s as: %s", testPhrase, err)
	}

	for i, e := range animes {
		bytes, err := json.Marshal(e)
		if err != nil {
			t.Errorf("searcher: couldn't marshal anime struct to json: %s", err)
		}

		animeJson := string(bytes)
		if animeJson != testJsonArr[i] {
			t.Errorf("searcher:\nexpected: %s\ngot: %s\n", testJsonArr[i], animeJson)
		}
	}
}
